<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />

  <ItemGroup>
    <PackageReference Include="Defra.Livestock.Sdk.Api.Strategies" />
    <PackageReference Include="PDFtoImage" />
    <PackageReference Include="SkiaSharp" />
  </ItemGroup>
</Project>
